### ISSUE TITLE
404 page werkt niet voor student

### ISSUE THREAD

**Issue by KokoDoko** [bpikaar/buildingblocks#30]
404 page / error page toevoegen.

**Comment by KokoDoko** [comment]
Pagina toegevoegd, werkt voor http://bb.app/onzin en voor http://bb.app/docent/onzin maar niet voor http://bb.app/student/onzin, heeft de student view al een redirect ergens @bpikaar ?

**Comment by bpikaar** [comment]
Ook bij studenten werkt het http://bb.app/student/bs/onzin 
Punt is alleen dat domein/student/iets een filter pagina is. Je kunt als alles meegeven maar filtert alleen op 'complete' en op 'date'
