### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by KokoDoko** [bpikaar/buildingblocks#53]
Routing leesbaarder maken, plus direct benaderbaar via url:

http://bb.app/assessment/make/1
http://bb.app/assessment/make/2

wordt dan bijvoorbeeld:

http://bb.app/mooie-dingen-programmeren/                               <- link naar bb beschrijving
http://bb.app/mooie-dingen-programmeren/assessment/          <- in beschrijving geklikt op inplannen
- [x] student/bb-name/details
- [x] student/bb-name/assessment
- [ ] docent/bb-name/bewerken
- [ ] docent/studentFullName/details (overzichtspagina bb's voor student)
- [ ] docent/studentFullName/bb-name (details)

**Comment by bpikaar** [comment]
http://stackoverflow.com/questions/23145245/laravel-creating-dynamic-routes-to-controllers-from-mysql-database

**Comment by bpikaar** [comment]
- [ ] student/bb-name/details
- [ ] student/bb-name/assessment
- [ ] docent/bb-name/bewerken
- [ ] docent/studentFullName/details (overzichtspagina bb's voor student)
- [ ] docent/studentFullName/bb-name (details)
