### ISSUE TITLE
BB handboek != single page

### ISSUE THREAD

**Issue by bpikaar** [bpikaar/buildingblocks#60]
Studenten ervaren de pagina als lang en onoverzichtelijk. 
Het zou beter zijn om op de BB's te kunnen klikken en dat dan ALLEEN dat bb geladen wordt. 
Je bent ook niet op zoek naar die andere, dan klik je wel weer. 

De tekst boven de blokken mag ook wel weg.

**Comment by KokoDoko** [comment]
OK, dan laten we het BB handbook helemaal weg, want die individuele beschrijving krijg je ook als je via 'mijn building blocks' op een BB klikt. Het zij-menu verplaats ik dan naar de BB detail page.

**Comment by bpikaar** [comment]
Laat het nog maar even staan. We kunnen met deze pagina testen en altijd nog weghalen. Ik kan aan de statistieken zien hoe vaak de pagina bezocht wordt.

**Comment by KokoDoko** [comment]
Too late :) Kijk maar even of je het zo beter vind, ik vind het zelf wel duidelijker. De pagina bestaat nog wel maar staat niet meer in het menu.
