### ISSUE TITLE
Melding "Niet bevestigd" kan misschien ook over een rood vlak komen

### ISSUE THREAD

**Issue by bpikaar** [bpikaar/buildingblocks#67]
dan is het niet te lezen

**Comment by KokoDoko** [comment]
Het blok wordt pas rood als je je beide herkansingen hebt gemist, dan kan je geen afspraak meer maken.
Als je een herkansing mag doen is het blok geel.

![Datum niet bevestigd](http://projects.eerkmans.nl/bestanden/bb_geelrood.png)
